#!/bin/bash

#

#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --time=24:00:00
#SBATCH --mem=115GB
#SBATCH --job-name=q1.1
#SBATCH --array=1-22

module load bwa/intel/0.7.15

echo The array index is: "${SLURM_ARRAY_TASK_ID}"

ref=/scratch/ava278/hw4/indexes/Homo_sapiens.GRCh38.dna_sm.primary_assembly.normalized.fa
table=table.txt
line="$(head -n ${SLURM_ARRAY_TASK_ID} "${table}" | tail -n 1)"
sample="$(printf "%s" "${line}" | cut -f1)"
fq1="$(printf "%s" "${line}" | cut –f2)"
fq2="$(printf "%s" "${line}" | cut –f3)"
pathtofqs=/scratch/ava278/trimmedfastqs

mkdir "${sample}"
cd "${sample}"

bwa mem -t "${SLURM_CPUS_PER_TASK}" -R "@RG\tID:"${sample}".id\tSM:"${sample}"\tPL:Illumina\tLB:"${sample}".lb" "${ref}" \
"${pathtofqs}${fq1}" "${pathtofqs}${fq2}" > "${sample}".sam
